// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: task.proto

package taskservice

import (
	"context"

	"video-in-chinese/server/mcp/task-gozero/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateTaskRequest     = proto.CreateTaskRequest
	CreateTaskResponse    = proto.CreateTaskResponse
	GetTaskStatusRequest  = proto.GetTaskStatusRequest
	GetTaskStatusResponse = proto.GetTaskStatusResponse

	TaskService interface {
		// CreateTask 创建新任务
		CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
		// GetTaskStatus 查询任务状态
		GetTaskStatus(ctx context.Context, in *GetTaskStatusRequest, opts ...grpc.CallOption) (*GetTaskStatusResponse, error)
	}

	defaultTaskService struct {
		cli zrpc.Client
	}
)

func NewTaskService(cli zrpc.Client) TaskService {
	return &defaultTaskService{
		cli: cli,
	}
}

// CreateTask 创建新任务
func (m *defaultTaskService) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	client := proto.NewTaskServiceClient(m.cli.Conn())
	return client.CreateTask(ctx, in, opts...)
}

// GetTaskStatus 查询任务状态
func (m *defaultTaskService) GetTaskStatus(ctx context.Context, in *GetTaskStatusRequest, opts ...grpc.CallOption) (*GetTaskStatusResponse, error) {
	client := proto.NewTaskServiceClient(m.cli.Conn())
	return client.GetTaskStatus(ctx, in, opts...)
}
