// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type DownloadFileRequest struct {
	TaskId   string `path:"taskId"`   // [必需] 文件所属的任务ID。
	FileName string `path:"fileName"` // [必需] 要下载的文件名, 例如 "result.mp4" 或 "original.mp4"。
}

type GetSettingsResponse struct {
	Version                         int64  `json:"version"`                             // [必需] 配置版本号，用于乐观锁。
	IsConfigured                    bool   `json:"is_configured"`                       // [必需] 系统是否已完成基本配置。判断逻辑：至少配置了 ASR、Translation、VoiceCloning 三个必需服务的 API Key。如果为 false，前端应显示"初始化向导"引导用户完成配置。
	ProcessingMode                  string `json:"processing_mode"`                     // [必需] 视频处理模式。V1.0仅支持 "standard"。
	AsrProvider                     string `json:"asr_provider"`                        // [条件性必需] ASR服务商标识。
	AsrApiKey                       string `json:"asr_api_key"`                         // [条件性必需] 脱敏后的API Key。
	AsrEndpoint                     string `json:"asr_endpoint,omitempty"`              // [可选] 自定义的服务端点URL。
	AudioSeparationEnabled          bool   `json:"audio_separation_enabled"`            // [必需] 是否启用音频分离（需要GPU）。默认 false。
	PolishingEnabled                bool   `json:"polishing_enabled"`                   // [必需] 是否启用文本润色功能。
	PolishingProvider               string `json:"polishing_provider,omitempty"`        // [可选] 文本润色服务商标识。
	PolishingApiKey                 string `json:"polishing_api_key,omitempty"`         // [可选] 脱敏后的API Key。
	PolishingEndpoint               string `json:"polishing_endpoint,omitempty"`        // [可选] 自定义的服务端点URL。
	PolishingCustomPrompt           string `json:"polishing_custom_prompt,omitempty"`   // [可选] 用户自定义的润色 Prompt。
	PolishingVideoType              string `json:"polishing_video_type,omitempty"`      // [可选] 翻译预设类型："professional_tech"（专业科技）、"casual_natural"（口语自然）、"educational_rigorous"（教育严谨）。
	TranslationProvider             string `json:"translation_provider"`                // [条件性必需] 翻译服务商标识。
	TranslationApiKey               string `json:"translation_api_key"`                 // [条件性必需] 脱敏后的API Key。
	TranslationEndpoint             string `json:"translation_endpoint,omitempty"`      // [可选] 自定义的服务端点URL。
	TranslationVideoType            string `json:"translation_video_type,omitempty"`    // [可选] 翻译预设类型："professional_tech"（专业科技）、"casual_natural"（口语自然）、"educational_rigorous"（教育严谨）。
	OptimizationEnabled             bool   `json:"optimization_enabled"`                // [必需] 是否启用译文优化功能。
	OptimizationProvider            string `json:"optimization_provider,omitempty"`     // [可选] 译文优化服务商标识。
	OptimizationApiKey              string `json:"optimization_api_key,omitempty"`      // [可选] 脱敏后的API Key。
	OptimizationEndpoint            string `json:"optimization_endpoint,omitempty"`     // [可选] 自定义的服务端点URL。
	VoiceCloningProvider            string `json:"voice_cloning_provider"`              // [条件性必需] 声音克隆服务商标识。
	VoiceCloningApiKey              string `json:"voice_cloning_api_key"`               // [条件性必需] 脱敏后的API Key。
	VoiceCloningEndpoint            string `json:"voice_cloning_endpoint,omitempty"`    // [可选] 自定义的服务端点URL。
	VoiceCloningAutoSelectReference bool   `json:"voice_cloning_auto_select_reference"` // [必需] 是否自动选择参考音频。默认 true。
	S2stProvider                    string `json:"s2st_provider,omitempty"`             // [可选] S2ST服务商标识。
	S2stApiKey                      string `json:"s2st_api_key,omitempty"`              // [可选] 脱敏后的API Key。
}

type GetTaskStatusRequest struct {
	TaskId string `path:"taskId"` // [必需] 需要查询的任务ID。
}

type GetTaskStatusResponse struct {
	TaskId       string `json:"task_id"`                 // [必需] 任务ID。
	Status       string `json:"status"`                  // [必需] 任务当前状态: "PENDING", "PROCESSING", "COMPLETED", "FAILED"。
	ResultUrl    string `json:"result_url,omitempty"`    // [可选] 仅在任务状态为 "COMPLETED" 时出现。格式为 "/v1/tasks/download/{taskId}/{fileName}"。
	ErrorMessage string `json:"error_message,omitempty"` // [可选] 仅在任务状态为 "FAILED" 时出现，包含失败原因。
}

type UpdateSettingsRequest struct {
	Version                         int64  `json:"version"`                                       // [必需] 当前配置的版本号，用于乐观锁检查。
	ProcessingMode                  string `json:"processing_mode,omitempty"`                     // [可选] 更新处理模式。
	AsrProvider                     string `json:"asr_provider,omitempty"`                        // [可选] ASR服务商标识。
	AsrApiKey                       string `json:"asr_api_key,omitempty"`                         // [可选] 如果包含"***"则保持原值。
	AsrEndpoint                     string `json:"asr_endpoint,omitempty"`                        // [可选] 自定义端点URL。
	AudioSeparationEnabled          *bool  `json:"audio_separation_enabled,omitempty"`            // [可选] 是否启用音频分离。使用指针类型以区分 "未提交" 和 "提交了false值"。
	PolishingEnabled                *bool  `json:"polishing_enabled,omitempty"`                   // [可选] 使用指针类型以区分 "未提交" 和 "提交了false值"。
	PolishingProvider               string `json:"polishing_provider,omitempty"`                  // [可选] 文本润色服务商标识。
	PolishingApiKey                 string `json:"polishing_api_key,omitempty"`                   // [可选] 如果包含"***"则保持原值。
	PolishingEndpoint               string `json:"polishing_endpoint,omitempty"`                  // [可选] 自定义端点URL。
	PolishingCustomPrompt           string `json:"polishing_custom_prompt,omitempty"`             // [可选] 用户自定义的润色 Prompt。
	PolishingVideoType              string `json:"polishing_video_type,omitempty"`                // [可选] 翻译预设类型。
	TranslationProvider             string `json:"translation_provider,omitempty"`                // [可选] 翻译服务商标识。
	TranslationApiKey               string `json:"translation_api_key,omitempty"`                 // [可选] 如果包含"***"则保持原值。
	TranslationEndpoint             string `json:"translation_endpoint,omitempty"`                // [可选] 自定义端点URL。
	TranslationVideoType            string `json:"translation_video_type,omitempty"`              // [可选] 翻译预设类型。
	OptimizationEnabled             *bool  `json:"optimization_enabled,omitempty"`                // [可选] 是否启用译文优化。
	OptimizationProvider            string `json:"optimization_provider,omitempty"`               // [可选] 译文优化服务商标识。
	OptimizationApiKey              string `json:"optimization_api_key,omitempty"`                // [可选] 如果包含"***"则保持原值。
	OptimizationEndpoint            string `json:"optimization_endpoint,omitempty"`               // [可选] 自定义端点URL。
	VoiceCloningProvider            string `json:"voice_cloning_provider,omitempty"`              // [可选] 声音克隆服务商标识。
	VoiceCloningApiKey              string `json:"voice_cloning_api_key,omitempty"`               // [可选] 如果包含"***"则保持原值。
	VoiceCloningEndpoint            string `json:"voice_cloning_endpoint,omitempty"`              // [可选] 自定义端点URL。
	VoiceCloningAutoSelectReference *bool  `json:"voice_cloning_auto_select_reference,omitempty"` // [可选] 是否自动选择参考音频。
	S2stProvider                    string `json:"s2st_provider,omitempty"`                       // [可选] S2ST服务商标识。
	S2stApiKey                      string `json:"s2st_api_key,omitempty"`                        // [可选] 如果包含"***"则保持原值。
}

type UpdateSettingsResponse struct {
	Version int64  `json:"version"` // [必需] 更新成功后，返回新的配置版本号。
	Message string `json:"message"` // [必需] 成功提示信息，例如 "配置已成功更新"。
}

type UploadTaskResponse struct {
	TaskId string `json:"task_id"` // [必需] 创建成功后返回的唯一任务ID。
}
