// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: pb/audioseparator.proto

package audioseparator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分离音频请求
type SeparateAudioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioPath     string                 `protobuf:"bytes,1,opt,name=audio_path,json=audioPath,proto3" json:"audio_path,omitempty"` // 输入音频文件的绝对路径
	OutputDir     string                 `protobuf:"bytes,2,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"` // 输出目录的绝对路径
	Stems         int32                  `protobuf:"varint,3,opt,name=stems,proto3" json:"stems,omitempty"`                         // 分离模式，2/4/5 stems，0 表示使用默认值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeparateAudioRequest) Reset() {
	*x = SeparateAudioRequest{}
	mi := &file_pb_audioseparator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeparateAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeparateAudioRequest) ProtoMessage() {}

func (x *SeparateAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_audioseparator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeparateAudioRequest.ProtoReflect.Descriptor instead.
func (*SeparateAudioRequest) Descriptor() ([]byte, []int) {
	return file_pb_audioseparator_proto_rawDescGZIP(), []int{0}
}

func (x *SeparateAudioRequest) GetAudioPath() string {
	if x != nil {
		return x.AudioPath
	}
	return ""
}

func (x *SeparateAudioRequest) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *SeparateAudioRequest) GetStems() int32 {
	if x != nil {
		return x.Stems
	}
	return 0
}

// 分离结果中的单个 stem 文件
type SeparatedStem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // stem 名称（如 vocals、drums）
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"` // 对应输出文件的绝对路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeparatedStem) Reset() {
	*x = SeparatedStem{}
	mi := &file_pb_audioseparator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeparatedStem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeparatedStem) ProtoMessage() {}

func (x *SeparatedStem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_audioseparator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeparatedStem.ProtoReflect.Descriptor instead.
func (*SeparatedStem) Descriptor() ([]byte, []int) {
	return file_pb_audioseparator_proto_rawDescGZIP(), []int{1}
}

func (x *SeparatedStem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SeparatedStem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// 分离音频响应
type SeparateAudioResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                             // 是否成功
	VocalsPath        string                 `protobuf:"bytes,2,opt,name=vocals_path,json=vocalsPath,proto3" json:"vocals_path,omitempty"`                      // 人声文件路径（兼容字段）
	AccompanimentPath string                 `protobuf:"bytes,3,opt,name=accompaniment_path,json=accompanimentPath,proto3" json:"accompaniment_path,omitempty"` // 背景音文件路径（兼容字段）
	ErrorMessage      string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                // 错误信息（如果失败）
	ProcessingTimeMs  int32                  `protobuf:"varint,5,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"` // 处理耗时（毫秒）
	Stems             []*SeparatedStem       `protobuf:"bytes,6,rep,name=stems,proto3" json:"stems,omitempty"`                                                  // 全量 stems 输出列表
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SeparateAudioResponse) Reset() {
	*x = SeparateAudioResponse{}
	mi := &file_pb_audioseparator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeparateAudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeparateAudioResponse) ProtoMessage() {}

func (x *SeparateAudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_audioseparator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeparateAudioResponse.ProtoReflect.Descriptor instead.
func (*SeparateAudioResponse) Descriptor() ([]byte, []int) {
	return file_pb_audioseparator_proto_rawDescGZIP(), []int{2}
}

func (x *SeparateAudioResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SeparateAudioResponse) GetVocalsPath() string {
	if x != nil {
		return x.VocalsPath
	}
	return ""
}

func (x *SeparateAudioResponse) GetAccompanimentPath() string {
	if x != nil {
		return x.AccompanimentPath
	}
	return ""
}

func (x *SeparateAudioResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SeparateAudioResponse) GetProcessingTimeMs() int32 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

func (x *SeparateAudioResponse) GetStems() []*SeparatedStem {
	if x != nil {
		return x.Stems
	}
	return nil
}

var File_pb_audioseparator_proto protoreflect.FileDescriptor

const file_pb_audioseparator_proto_rawDesc = "" +
	"\n" +
	"\x17pb/audioseparator.proto\x12\x0eaudioseparator\"j\n" +
	"\x14SeparateAudioRequest\x12\x1d\n" +
	"\n" +
	"audio_path\x18\x01 \x01(\tR\taudioPath\x12\x1d\n" +
	"\n" +
	"output_dir\x18\x02 \x01(\tR\toutputDir\x12\x14\n" +
	"\x05stems\x18\x03 \x01(\x05R\x05stems\"7\n" +
	"\rSeparatedStem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x89\x02\n" +
	"\x15SeparateAudioResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vvocals_path\x18\x02 \x01(\tR\n" +
	"vocalsPath\x12-\n" +
	"\x12accompaniment_path\x18\x03 \x01(\tR\x11accompanimentPath\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12,\n" +
	"\x12processing_time_ms\x18\x05 \x01(\x05R\x10processingTimeMs\x123\n" +
	"\x05stems\x18\x06 \x03(\v2\x1d.audioseparator.SeparatedStemR\x05stems2n\n" +
	"\x0eAudioSeparator\x12\\\n" +
	"\rSeparateAudio\x12$.audioseparator.SeparateAudioRequest\x1a%.audioseparator.SeparateAudioResponseB\x12Z\x10./audioseparatorb\x06proto3"

var (
	file_pb_audioseparator_proto_rawDescOnce sync.Once
	file_pb_audioseparator_proto_rawDescData []byte
)

func file_pb_audioseparator_proto_rawDescGZIP() []byte {
	file_pb_audioseparator_proto_rawDescOnce.Do(func() {
		file_pb_audioseparator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_audioseparator_proto_rawDesc), len(file_pb_audioseparator_proto_rawDesc)))
	})
	return file_pb_audioseparator_proto_rawDescData
}

var file_pb_audioseparator_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_audioseparator_proto_goTypes = []any{
	(*SeparateAudioRequest)(nil),  // 0: audioseparator.SeparateAudioRequest
	(*SeparatedStem)(nil),         // 1: audioseparator.SeparatedStem
	(*SeparateAudioResponse)(nil), // 2: audioseparator.SeparateAudioResponse
}
var file_pb_audioseparator_proto_depIdxs = []int32{
	1, // 0: audioseparator.SeparateAudioResponse.stems:type_name -> audioseparator.SeparatedStem
	0, // 1: audioseparator.AudioSeparator.SeparateAudio:input_type -> audioseparator.SeparateAudioRequest
	2, // 2: audioseparator.AudioSeparator.SeparateAudio:output_type -> audioseparator.SeparateAudioResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_audioseparator_proto_init() }
func file_pb_audioseparator_proto_init() {
	if File_pb_audioseparator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_audioseparator_proto_rawDesc), len(file_pb_audioseparator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_audioseparator_proto_goTypes,
		DependencyIndexes: file_pb_audioseparator_proto_depIdxs,
		MessageInfos:      file_pb_audioseparator_proto_msgTypes,
	}.Build()
	File_pb_audioseparator_proto = out.File
	file_pb_audioseparator_proto_goTypes = nil
	file_pb_audioseparator_proto_depIdxs = nil
}
