# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import audioseparator_pb2 as audioseparator__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in audioseparator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioSeparatorStub(object):
    """AudioSeparator 服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SeparateAudio = channel.unary_unary(
                '/audioseparator.AudioSeparator/SeparateAudio',
                request_serializer=audioseparator__pb2.SeparateAudioRequest.SerializeToString,
                response_deserializer=audioseparator__pb2.SeparateAudioResponse.FromString,
                _registered_method=True)


class AudioSeparatorServicer(object):
    """AudioSeparator 服务定义
    """

    def SeparateAudio(self, request, context):
        """分离音频为多种 stems
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioSeparatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SeparateAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.SeparateAudio,
                    request_deserializer=audioseparator__pb2.SeparateAudioRequest.FromString,
                    response_serializer=audioseparator__pb2.SeparateAudioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audioseparator.AudioSeparator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('audioseparator.AudioSeparator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioSeparator(object):
    """AudioSeparator 服务定义
    """

    @staticmethod
    def SeparateAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audioseparator.AudioSeparator/SeparateAudio',
            audioseparator__pb2.SeparateAudioRequest.SerializeToString,
            audioseparator__pb2.SeparateAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
