# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audioseparator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'audioseparator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61udioseparator.proto\x12\x0e\x61udioseparator\"M\n\x14SeparateAudioRequest\x12\x12\n\naudio_path\x18\x01 \x01(\t\x12\x12\n\noutput_dir\x18\x02 \x01(\t\x12\r\n\x05stems\x18\x03 \x01(\x05\"+\n\rSeparatedStem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"\xba\x01\n\x15SeparateAudioResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bvocals_path\x18\x02 \x01(\t\x12\x1a\n\x12\x61\x63\x63ompaniment_path\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12\x1a\n\x12processing_time_ms\x18\x05 \x01(\x05\x12,\n\x05stems\x18\x06 \x03(\x0b\x32\x1d.audioseparator.SeparatedStem2n\n\x0e\x41udioSeparator\x12\\\n\rSeparateAudio\x12$.audioseparator.SeparateAudioRequest\x1a%.audioseparator.SeparateAudioResponseB\x12Z\x10./audioseparatorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audioseparator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020./audioseparator'
  _globals['_SEPARATEAUDIOREQUEST']._serialized_start=40
  _globals['_SEPARATEAUDIOREQUEST']._serialized_end=117
  _globals['_SEPARATEDSTEM']._serialized_start=119
  _globals['_SEPARATEDSTEM']._serialized_end=162
  _globals['_SEPARATEAUDIORESPONSE']._serialized_start=165
  _globals['_SEPARATEAUDIORESPONSE']._serialized_end=351
  _globals['_AUDIOSEPARATOR']._serialized_start=353
  _globals['_AUDIOSEPARATOR']._serialized_end=463
# @@protoc_insertion_point(module_scope)
