// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: proto/aiadaptor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIAdaptor_ASR_FullMethodName        = "/aiadaptor.AIAdaptor/ASR"
	AIAdaptor_Polish_FullMethodName     = "/aiadaptor.AIAdaptor/Polish"
	AIAdaptor_Translate_FullMethodName  = "/aiadaptor.AIAdaptor/Translate"
	AIAdaptor_Optimize_FullMethodName   = "/aiadaptor.AIAdaptor/Optimize"
	AIAdaptor_CloneVoice_FullMethodName = "/aiadaptor.AIAdaptor/CloneVoice"
)

// AIAdaptorClient is the client API for AIAdaptor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AIAdaptor 服务定义
type AIAdaptorClient interface {
	// ASR（语音识别 + 说话人日志）
	ASR(ctx context.Context, in *ASRRequest, opts ...grpc.CallOption) (*ASRResponse, error)
	// 文本润色
	Polish(ctx context.Context, in *PolishRequest, opts ...grpc.CallOption) (*PolishResponse, error)
	// 翻译
	Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (*TranslateResponse, error)
	// 译文优化
	Optimize(ctx context.Context, in *OptimizeRequest, opts ...grpc.CallOption) (*OptimizeResponse, error)
	// 声音克隆
	CloneVoice(ctx context.Context, in *CloneVoiceRequest, opts ...grpc.CallOption) (*CloneVoiceResponse, error)
}

type aIAdaptorClient struct {
	cc grpc.ClientConnInterface
}

func NewAIAdaptorClient(cc grpc.ClientConnInterface) AIAdaptorClient {
	return &aIAdaptorClient{cc}
}

func (c *aIAdaptorClient) ASR(ctx context.Context, in *ASRRequest, opts ...grpc.CallOption) (*ASRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ASRResponse)
	err := c.cc.Invoke(ctx, AIAdaptor_ASR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIAdaptorClient) Polish(ctx context.Context, in *PolishRequest, opts ...grpc.CallOption) (*PolishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolishResponse)
	err := c.cc.Invoke(ctx, AIAdaptor_Polish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIAdaptorClient) Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (*TranslateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranslateResponse)
	err := c.cc.Invoke(ctx, AIAdaptor_Translate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIAdaptorClient) Optimize(ctx context.Context, in *OptimizeRequest, opts ...grpc.CallOption) (*OptimizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OptimizeResponse)
	err := c.cc.Invoke(ctx, AIAdaptor_Optimize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIAdaptorClient) CloneVoice(ctx context.Context, in *CloneVoiceRequest, opts ...grpc.CallOption) (*CloneVoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloneVoiceResponse)
	err := c.cc.Invoke(ctx, AIAdaptor_CloneVoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIAdaptorServer is the server API for AIAdaptor service.
// All implementations must embed UnimplementedAIAdaptorServer
// for forward compatibility.
//
// AIAdaptor 服务定义
type AIAdaptorServer interface {
	// ASR（语音识别 + 说话人日志）
	ASR(context.Context, *ASRRequest) (*ASRResponse, error)
	// 文本润色
	Polish(context.Context, *PolishRequest) (*PolishResponse, error)
	// 翻译
	Translate(context.Context, *TranslateRequest) (*TranslateResponse, error)
	// 译文优化
	Optimize(context.Context, *OptimizeRequest) (*OptimizeResponse, error)
	// 声音克隆
	CloneVoice(context.Context, *CloneVoiceRequest) (*CloneVoiceResponse, error)
	mustEmbedUnimplementedAIAdaptorServer()
}

// UnimplementedAIAdaptorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIAdaptorServer struct{}

func (UnimplementedAIAdaptorServer) ASR(context.Context, *ASRRequest) (*ASRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ASR not implemented")
}
func (UnimplementedAIAdaptorServer) Polish(context.Context, *PolishRequest) (*PolishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Polish not implemented")
}
func (UnimplementedAIAdaptorServer) Translate(context.Context, *TranslateRequest) (*TranslateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Translate not implemented")
}
func (UnimplementedAIAdaptorServer) Optimize(context.Context, *OptimizeRequest) (*OptimizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Optimize not implemented")
}
func (UnimplementedAIAdaptorServer) CloneVoice(context.Context, *CloneVoiceRequest) (*CloneVoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloneVoice not implemented")
}
func (UnimplementedAIAdaptorServer) mustEmbedUnimplementedAIAdaptorServer() {}
func (UnimplementedAIAdaptorServer) testEmbeddedByValue()                   {}

// UnsafeAIAdaptorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIAdaptorServer will
// result in compilation errors.
type UnsafeAIAdaptorServer interface {
	mustEmbedUnimplementedAIAdaptorServer()
}

func RegisterAIAdaptorServer(s grpc.ServiceRegistrar, srv AIAdaptorServer) {
	// If the following call pancis, it indicates UnimplementedAIAdaptorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIAdaptor_ServiceDesc, srv)
}

func _AIAdaptor_ASR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ASRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIAdaptorServer).ASR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIAdaptor_ASR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIAdaptorServer).ASR(ctx, req.(*ASRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIAdaptor_Polish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIAdaptorServer).Polish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIAdaptor_Polish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIAdaptorServer).Polish(ctx, req.(*PolishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIAdaptor_Translate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIAdaptorServer).Translate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIAdaptor_Translate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIAdaptorServer).Translate(ctx, req.(*TranslateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIAdaptor_Optimize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIAdaptorServer).Optimize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIAdaptor_Optimize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIAdaptorServer).Optimize(ctx, req.(*OptimizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIAdaptor_CloneVoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneVoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIAdaptorServer).CloneVoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIAdaptor_CloneVoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIAdaptorServer).CloneVoice(ctx, req.(*CloneVoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIAdaptor_ServiceDesc is the grpc.ServiceDesc for AIAdaptor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIAdaptor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aiadaptor.AIAdaptor",
	HandlerType: (*AIAdaptorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ASR",
			Handler:    _AIAdaptor_ASR_Handler,
		},
		{
			MethodName: "Polish",
			Handler:    _AIAdaptor_Polish_Handler,
		},
		{
			MethodName: "Translate",
			Handler:    _AIAdaptor_Translate_Handler,
		},
		{
			MethodName: "Optimize",
			Handler:    _AIAdaptor_Optimize_Handler,
		},
		{
			MethodName: "CloneVoice",
			Handler:    _AIAdaptor_CloneVoice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/aiadaptor.proto",
}
