// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: proto/aiadaptor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ASR 请求
type ASRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioPath     string                 `protobuf:"bytes,1,opt,name=audio_path,json=audioPath,proto3" json:"audio_path,omitempty"` // 音频文件路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASRRequest) Reset() {
	*x = ASRRequest{}
	mi := &file_proto_aiadaptor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASRRequest) ProtoMessage() {}

func (x *ASRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiadaptor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASRRequest.ProtoReflect.Descriptor instead.
func (*ASRRequest) Descriptor() ([]byte, []int) {
	return file_proto_aiadaptor_proto_rawDescGZIP(), []int{0}
}

func (x *ASRRequest) GetAudioPath() string {
	if x != nil {
		return x.AudioPath
	}
	return ""
}

// ASR 响应
type ASRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Speakers      []*Speaker             `protobuf:"bytes,1,rep,name=speakers,proto3" json:"speakers,omitempty"` // 说话人列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASRResponse) Reset() {
	*x = ASRResponse{}
	mi := &file_proto_aiadaptor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASRResponse) ProtoMessage() {}

func (x *ASRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiadaptor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASRResponse.ProtoReflect.Descriptor instead.
func (*ASRResponse) Descriptor() ([]byte, []int) {
	return file_proto_aiadaptor_proto_rawDescGZIP(), []int{1}
}

func (x *ASRResponse) GetSpeakers() []*Speaker {
	if x != nil {
		return x.Speakers
	}
	return nil
}

type Speaker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpeakerId     string                 `protobuf:"bytes,1,opt,name=speaker_id,json=speakerId,proto3" json:"speaker_id,omitempty"` // 说话人 ID
	Sentences     []*Sentence            `protobuf:"bytes,2,rep,name=sentences,proto3" json:"sentences,omitempty"`                  // 句子列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Speaker) Reset() {
	*x = Speaker{}
	mi := &file_proto_aiadaptor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Speaker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Speaker) ProtoMessage() {}

func (x *Speaker) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiadaptor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Speaker.ProtoReflect.Descriptor instead.
func (*Speaker) Descriptor() ([]byte, []int) {
	return file_proto_aiadaptor_proto_rawDescGZIP(), []int{2}
}

func (x *Speaker) GetSpeakerId() string {
	if x != nil {
		return x.SpeakerId
	}
	return ""
}

func (x *Speaker) GetSentences() []*Sentence {
	if x != nil {
		return x.Sentences
	}
	return nil
}

type Sentence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                              // 文本内容
	StartTime     float64                `protobuf:"fixed64,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 开始时间（秒）
	EndTime       float64                `protobuf:"fixed64,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // 结束时间（秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sentence) Reset() {
	*x = Sentence{}
	mi := &file_proto_aiadaptor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sentence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sentence) ProtoMessage() {}

func (x *Sentence) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiadaptor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sentence.ProtoReflect.Descriptor instead.
func (*Sentence) Descriptor() ([]byte, []int) {
	return file_proto_aiadaptor_proto_rawDescGZIP(), []int{3}
}

func (x *Sentence) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Sentence) GetStartTime() float64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Sentence) GetEndTime() float64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// 文本润色请求
type PolishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                                     // 原始文本
	VideoType     string                 `protobuf:"bytes,2,opt,name=video_type,json=videoType,proto3" json:"video_type,omitempty"`          // 视频类型（professional_tech, casual_natural, educational_rigorous, default）
	CustomPrompt  string                 `protobuf:"bytes,3,opt,name=custom_prompt,json=customPrompt,proto3" json:"custom_prompt,omitempty"` // 用户自定义 Prompt（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolishRequest) Reset() {
	*x = PolishRequest{}
	mi := &file_proto_aiadaptor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolishRequest) ProtoMessage() {}

func (x *PolishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiadaptor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolishRequest.ProtoReflect.Descriptor instead.
func (*PolishRequest) Descriptor() ([]byte, []int) {
	return file_proto_aiadaptor_proto_rawDescGZIP(), []int{4}
}

func (x *PolishRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PolishRequest) GetVideoType() string {
	if x != nil {
		return x.VideoType
	}
	return ""
}

func (x *PolishRequest) GetCustomPrompt() string {
	if x != nil {
		return x.CustomPrompt
	}
	return ""
}

// 文本润色响应
type PolishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolishedText  string                 `protobuf:"bytes,1,opt,name=polished_text,json=polishedText,proto3" json:"polished_text,omitempty"` // 润色后的文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolishResponse) Reset() {
	*x = PolishResponse{}
	mi := &file_proto_aiadaptor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolishResponse) ProtoMessage() {}

func (x *PolishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiadaptor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolishResponse.ProtoReflect.Descriptor instead.
func (*PolishResponse) Descriptor() ([]byte, []int) {
	return file_proto_aiadaptor_proto_rawDescGZIP(), []int{5}
}

func (x *PolishResponse) GetPolishedText() string {
	if x != nil {
		return x.PolishedText
	}
	return ""
}

// 翻译请求
type TranslateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Text            string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                                                // ԭʼ�ı�
	SourceLang      string                 `protobuf:"bytes,2,opt,name=source_lang,json=sourceLang,proto3" json:"source_lang,omitempty"`                  // Դ���ԣ�Ĭ�� en��
	TargetLang      string                 `protobuf:"bytes,3,opt,name=target_lang,json=targetLang,proto3" json:"target_lang,omitempty"`                  // Ŀ�����ԣ�Ĭ�� zh��
	VideoType       string                 `protobuf:"bytes,4,opt,name=video_type,json=videoType,proto3" json:"video_type,omitempty"`                     // ��Ƶ���ͣ�professional_tech, casual_natural, educational_rigorous, default��
	DurationSeconds float64                `protobuf:"fixed64,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"` // ��Ӧԭ�����ʱ��(��)
	SpeakerRole     string                 `protobuf:"bytes,6,opt,name=speaker_role,json=speakerRole,proto3" json:"speaker_role,omitempty"`               // ˵��������ɫ/����
	TargetWordMin   uint32                 `protobuf:"varint,7,opt,name=target_word_min,json=targetWordMin,proto3" json:"target_word_min,omitempty"`      // Ԥ��͵�������
	TargetWordMax   uint32                 `protobuf:"varint,8,opt,name=target_word_max,json=targetWordMax,proto3" json:"target_word_max,omitempty"`      // Ԥ��ߵ�������
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TranslateRequest) Reset() {
	*x = TranslateRequest{}
	mi := &file_proto_aiadaptor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateRequest) ProtoMessage() {}

func (x *TranslateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiadaptor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateRequest.ProtoReflect.Descriptor instead.
func (*TranslateRequest) Descriptor() ([]byte, []int) {
	return file_proto_aiadaptor_proto_rawDescGZIP(), []int{6}
}

func (x *TranslateRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranslateRequest) GetSourceLang() string {
	if x != nil {
		return x.SourceLang
	}
	return ""
}

func (x *TranslateRequest) GetTargetLang() string {
	if x != nil {
		return x.TargetLang
	}
	return ""
}

func (x *TranslateRequest) GetVideoType() string {
	if x != nil {
		return x.VideoType
	}
	return ""
}

func (x *TranslateRequest) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *TranslateRequest) GetSpeakerRole() string {
	if x != nil {
		return x.SpeakerRole
	}
	return ""
}

func (x *TranslateRequest) GetTargetWordMin() uint32 {
	if x != nil {
		return x.TargetWordMin
	}
	return 0
}

func (x *TranslateRequest) GetTargetWordMax() uint32 {
	if x != nil {
		return x.TargetWordMax
	}
	return 0
}

type TranslateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TranslatedText string                 `protobuf:"bytes,1,opt,name=translated_text,json=translatedText,proto3" json:"translated_text,omitempty"` // 翻译后的文本
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TranslateResponse) Reset() {
	*x = TranslateResponse{}
	mi := &file_proto_aiadaptor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateResponse) ProtoMessage() {}

func (x *TranslateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiadaptor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateResponse.ProtoReflect.Descriptor instead.
func (*TranslateResponse) Descriptor() ([]byte, []int) {
	return file_proto_aiadaptor_proto_rawDescGZIP(), []int{7}
}

func (x *TranslateResponse) GetTranslatedText() string {
	if x != nil {
		return x.TranslatedText
	}
	return ""
}

// 译文优化请求
type OptimizeRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Text                  string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                                                                    // �������ı�
	TargetDurationSeconds float64                `protobuf:"fixed64,2,opt,name=target_duration_seconds,json=targetDurationSeconds,proto3" json:"target_duration_seconds,omitempty"` // ���ĳ���ʱ�䣨�룩
	TargetWordMin         uint32                 `protobuf:"varint,3,opt,name=target_word_min,json=targetWordMin,proto3" json:"target_word_min,omitempty"`                          // Ԥ��͵�������
	TargetWordMax         uint32                 `protobuf:"varint,4,opt,name=target_word_max,json=targetWordMax,proto3" json:"target_word_max,omitempty"`                          // Ԥ��ߵ�������
	SpeakerRole           string                 `protobuf:"bytes,5,opt,name=speaker_role,json=speakerRole,proto3" json:"speaker_role,omitempty"`                                   // ˵��������ɫ/����
	VideoType             string                 `protobuf:"bytes,6,opt,name=video_type,json=videoType,proto3" json:"video_type,omitempty"`                                         // ��Ƶ����Ϣ�������������
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *OptimizeRequest) Reset() {
	*x = OptimizeRequest{}
	mi := &file_proto_aiadaptor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeRequest) ProtoMessage() {}

func (x *OptimizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiadaptor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeRequest.ProtoReflect.Descriptor instead.
func (*OptimizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_aiadaptor_proto_rawDescGZIP(), []int{8}
}

func (x *OptimizeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OptimizeRequest) GetTargetDurationSeconds() float64 {
	if x != nil {
		return x.TargetDurationSeconds
	}
	return 0
}

func (x *OptimizeRequest) GetTargetWordMin() uint32 {
	if x != nil {
		return x.TargetWordMin
	}
	return 0
}

func (x *OptimizeRequest) GetTargetWordMax() uint32 {
	if x != nil {
		return x.TargetWordMax
	}
	return 0
}

func (x *OptimizeRequest) GetSpeakerRole() string {
	if x != nil {
		return x.SpeakerRole
	}
	return ""
}

func (x *OptimizeRequest) GetVideoType() string {
	if x != nil {
		return x.VideoType
	}
	return ""
}

type OptimizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptimizedText string                 `protobuf:"bytes,1,opt,name=optimized_text,json=optimizedText,proto3" json:"optimized_text,omitempty"` // 优化后的文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizeResponse) Reset() {
	*x = OptimizeResponse{}
	mi := &file_proto_aiadaptor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeResponse) ProtoMessage() {}

func (x *OptimizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiadaptor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeResponse.ProtoReflect.Descriptor instead.
func (*OptimizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_aiadaptor_proto_rawDescGZIP(), []int{9}
}

func (x *OptimizeResponse) GetOptimizedText() string {
	if x != nil {
		return x.OptimizedText
	}
	return ""
}

// 声音克隆请求
type CloneVoiceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SpeakerId      string                 `protobuf:"bytes,1,opt,name=speaker_id,json=speakerId,proto3" json:"speaker_id,omitempty"`                // 说话人 ID（用于缓存）
	Text           string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                                           // 要合成的文本
	ReferenceAudio string                 `protobuf:"bytes,3,opt,name=reference_audio,json=referenceAudio,proto3" json:"reference_audio,omitempty"` // 参考音频路径
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CloneVoiceRequest) Reset() {
	*x = CloneVoiceRequest{}
	mi := &file_proto_aiadaptor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneVoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneVoiceRequest) ProtoMessage() {}

func (x *CloneVoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiadaptor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneVoiceRequest.ProtoReflect.Descriptor instead.
func (*CloneVoiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_aiadaptor_proto_rawDescGZIP(), []int{10}
}

func (x *CloneVoiceRequest) GetSpeakerId() string {
	if x != nil {
		return x.SpeakerId
	}
	return ""
}

func (x *CloneVoiceRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CloneVoiceRequest) GetReferenceAudio() string {
	if x != nil {
		return x.ReferenceAudio
	}
	return ""
}

// 声音克隆响应
type CloneVoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioPath     string                 `protobuf:"bytes,1,opt,name=audio_path,json=audioPath,proto3" json:"audio_path,omitempty"` // 合成的音频路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneVoiceResponse) Reset() {
	*x = CloneVoiceResponse{}
	mi := &file_proto_aiadaptor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneVoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneVoiceResponse) ProtoMessage() {}

func (x *CloneVoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiadaptor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneVoiceResponse.ProtoReflect.Descriptor instead.
func (*CloneVoiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_aiadaptor_proto_rawDescGZIP(), []int{11}
}

func (x *CloneVoiceResponse) GetAudioPath() string {
	if x != nil {
		return x.AudioPath
	}
	return ""
}

var File_proto_aiadaptor_proto protoreflect.FileDescriptor

const file_proto_aiadaptor_proto_rawDesc = "" +
	"\n" +
	"\x15proto/aiadaptor.proto\x12\taiadaptor\"+\n" +
	"\n" +
	"ASRRequest\x12\x1d\n" +
	"\n" +
	"audio_path\x18\x01 \x01(\tR\taudioPath\"=\n" +
	"\vASRResponse\x12.\n" +
	"\bspeakers\x18\x01 \x03(\v2\x12.aiadaptor.SpeakerR\bspeakers\"[\n" +
	"\aSpeaker\x12\x1d\n" +
	"\n" +
	"speaker_id\x18\x01 \x01(\tR\tspeakerId\x121\n" +
	"\tsentences\x18\x02 \x03(\v2\x13.aiadaptor.SentenceR\tsentences\"X\n" +
	"\bSentence\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x01R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x01R\aendTime\"g\n" +
	"\rPolishRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"video_type\x18\x02 \x01(\tR\tvideoType\x12#\n" +
	"\rcustom_prompt\x18\x03 \x01(\tR\fcustomPrompt\"5\n" +
	"\x0ePolishResponse\x12#\n" +
	"\rpolished_text\x18\x01 \x01(\tR\fpolishedText\"\xa5\x02\n" +
	"\x10TranslateRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1f\n" +
	"\vsource_lang\x18\x02 \x01(\tR\n" +
	"sourceLang\x12\x1f\n" +
	"\vtarget_lang\x18\x03 \x01(\tR\n" +
	"targetLang\x12\x1d\n" +
	"\n" +
	"video_type\x18\x04 \x01(\tR\tvideoType\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x01R\x0fdurationSeconds\x12!\n" +
	"\fspeaker_role\x18\x06 \x01(\tR\vspeakerRole\x12&\n" +
	"\x0ftarget_word_min\x18\a \x01(\rR\rtargetWordMin\x12&\n" +
	"\x0ftarget_word_max\x18\b \x01(\rR\rtargetWordMax\"<\n" +
	"\x11TranslateResponse\x12'\n" +
	"\x0ftranslated_text\x18\x01 \x01(\tR\x0etranslatedText\"\xef\x01\n" +
	"\x0fOptimizeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x126\n" +
	"\x17target_duration_seconds\x18\x02 \x01(\x01R\x15targetDurationSeconds\x12&\n" +
	"\x0ftarget_word_min\x18\x03 \x01(\rR\rtargetWordMin\x12&\n" +
	"\x0ftarget_word_max\x18\x04 \x01(\rR\rtargetWordMax\x12!\n" +
	"\fspeaker_role\x18\x05 \x01(\tR\vspeakerRole\x12\x1d\n" +
	"\n" +
	"video_type\x18\x06 \x01(\tR\tvideoType\"9\n" +
	"\x10OptimizeResponse\x12%\n" +
	"\x0eoptimized_text\x18\x01 \x01(\tR\roptimizedText\"o\n" +
	"\x11CloneVoiceRequest\x12\x1d\n" +
	"\n" +
	"speaker_id\x18\x01 \x01(\tR\tspeakerId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12'\n" +
	"\x0freference_audio\x18\x03 \x01(\tR\x0ereferenceAudio\"3\n" +
	"\x12CloneVoiceResponse\x12\x1d\n" +
	"\n" +
	"audio_path\x18\x01 \x01(\tR\taudioPath2\xd8\x02\n" +
	"\tAIAdaptor\x124\n" +
	"\x03ASR\x12\x15.aiadaptor.ASRRequest\x1a\x16.aiadaptor.ASRResponse\x12=\n" +
	"\x06Polish\x12\x18.aiadaptor.PolishRequest\x1a\x19.aiadaptor.PolishResponse\x12F\n" +
	"\tTranslate\x12\x1b.aiadaptor.TranslateRequest\x1a\x1c.aiadaptor.TranslateResponse\x12C\n" +
	"\bOptimize\x12\x1a.aiadaptor.OptimizeRequest\x1a\x1b.aiadaptor.OptimizeResponse\x12I\n" +
	"\n" +
	"CloneVoice\x12\x1c.aiadaptor.CloneVoiceRequest\x1a\x1d.aiadaptor.CloneVoiceResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_aiadaptor_proto_rawDescOnce sync.Once
	file_proto_aiadaptor_proto_rawDescData []byte
)

func file_proto_aiadaptor_proto_rawDescGZIP() []byte {
	file_proto_aiadaptor_proto_rawDescOnce.Do(func() {
		file_proto_aiadaptor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_aiadaptor_proto_rawDesc), len(file_proto_aiadaptor_proto_rawDesc)))
	})
	return file_proto_aiadaptor_proto_rawDescData
}

var file_proto_aiadaptor_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_aiadaptor_proto_goTypes = []any{
	(*ASRRequest)(nil),         // 0: aiadaptor.ASRRequest
	(*ASRResponse)(nil),        // 1: aiadaptor.ASRResponse
	(*Speaker)(nil),            // 2: aiadaptor.Speaker
	(*Sentence)(nil),           // 3: aiadaptor.Sentence
	(*PolishRequest)(nil),      // 4: aiadaptor.PolishRequest
	(*PolishResponse)(nil),     // 5: aiadaptor.PolishResponse
	(*TranslateRequest)(nil),   // 6: aiadaptor.TranslateRequest
	(*TranslateResponse)(nil),  // 7: aiadaptor.TranslateResponse
	(*OptimizeRequest)(nil),    // 8: aiadaptor.OptimizeRequest
	(*OptimizeResponse)(nil),   // 9: aiadaptor.OptimizeResponse
	(*CloneVoiceRequest)(nil),  // 10: aiadaptor.CloneVoiceRequest
	(*CloneVoiceResponse)(nil), // 11: aiadaptor.CloneVoiceResponse
}
var file_proto_aiadaptor_proto_depIdxs = []int32{
	2,  // 0: aiadaptor.ASRResponse.speakers:type_name -> aiadaptor.Speaker
	3,  // 1: aiadaptor.Speaker.sentences:type_name -> aiadaptor.Sentence
	0,  // 2: aiadaptor.AIAdaptor.ASR:input_type -> aiadaptor.ASRRequest
	4,  // 3: aiadaptor.AIAdaptor.Polish:input_type -> aiadaptor.PolishRequest
	6,  // 4: aiadaptor.AIAdaptor.Translate:input_type -> aiadaptor.TranslateRequest
	8,  // 5: aiadaptor.AIAdaptor.Optimize:input_type -> aiadaptor.OptimizeRequest
	10, // 6: aiadaptor.AIAdaptor.CloneVoice:input_type -> aiadaptor.CloneVoiceRequest
	1,  // 7: aiadaptor.AIAdaptor.ASR:output_type -> aiadaptor.ASRResponse
	5,  // 8: aiadaptor.AIAdaptor.Polish:output_type -> aiadaptor.PolishResponse
	7,  // 9: aiadaptor.AIAdaptor.Translate:output_type -> aiadaptor.TranslateResponse
	9,  // 10: aiadaptor.AIAdaptor.Optimize:output_type -> aiadaptor.OptimizeResponse
	11, // 11: aiadaptor.AIAdaptor.CloneVoice:output_type -> aiadaptor.CloneVoiceResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_aiadaptor_proto_init() }
func file_proto_aiadaptor_proto_init() {
	if File_proto_aiadaptor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_aiadaptor_proto_rawDesc), len(file_proto_aiadaptor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_aiadaptor_proto_goTypes,
		DependencyIndexes: file_proto_aiadaptor_proto_depIdxs,
		MessageInfos:      file_proto_aiadaptor_proto_msgTypes,
	}.Build()
	File_proto_aiadaptor_proto = out.File
	file_proto_aiadaptor_proto_goTypes = nil
	file_proto_aiadaptor_proto_depIdxs = nil
}
