// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: task.proto

package server

import (
	"context"

	"video-in-chinese/server/mcp/task/internal/logic"
	"video-in-chinese/server/mcp/task/internal/svc"
	"video-in-chinese/server/mcp/task/proto"
)

type TaskServiceServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedTaskServiceServer
}

func NewTaskServiceServer(svcCtx *svc.ServiceContext) *TaskServiceServer {
	return &TaskServiceServer{
		svcCtx: svcCtx,
	}
}

// CreateTask 创建新任务
func (s *TaskServiceServer) CreateTask(ctx context.Context, in *proto.CreateTaskRequest) (*proto.CreateTaskResponse, error) {
	l := logic.NewCreateTaskLogic(ctx, s.svcCtx)
	return l.CreateTask(in)
}

// GetTaskStatus 查询任务状态
func (s *TaskServiceServer) GetTaskStatus(ctx context.Context, in *proto.GetTaskStatusRequest) (*proto.GetTaskStatusResponse, error) {
	l := logic.NewGetTaskStatusLogic(ctx, s.svcCtx)
	return l.GetTaskStatus(in)
}
