// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	settings "video-in-chinese/server/app/gateway/internal/handler/settings"
	task "video-in-chinese/server/app/gateway/internal/handler/task"
	"video-in-chinese/server/app/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Get current application settings
				Method:  http.MethodGet,
				Path:    "/",
				Handler: settings.GetSettingsHandler(serverCtx),
			},
			{
				// Update application settings
				Method:  http.MethodPost,
				Path:    "/",
				Handler: settings.UpdateSettingsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/settings"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Get task status by task ID
				Method:  http.MethodGet,
				Path:    "/:taskId/status",
				Handler: task.GetTaskStatusHandler(serverCtx),
			},
			{
				// Download task result file
				Method:  http.MethodGet,
				Path:    "/download/:taskId/:fileName",
				Handler: task.DownloadFileHandler(serverCtx),
			},
			{
				// Upload a video file to create a new translation task
				Method:  http.MethodPost,
				Path:    "/upload",
				Handler: task.UploadTaskHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/tasks"),
	)
}
